on:
  schedule:
    - cron: '0 5 * * *'  
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install requests pandas openpyxl xlrd

      - name: Run script
        run: python auto_tracing_update.py

      - name: Commit and push updated Excel file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add TrackingSheet.xlsx
          git commit -m "Update Excel from GitHub Action"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



